# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_clavicle_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_effector:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_elbow:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_grip_x_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_grip_y_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_grip_z_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_clavicle_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_effector:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  right_elbow:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_grip_x_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_grip_y_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_grip_z_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0