# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_clavicle_joint
    - left_shoulder_joint
    - left_elbow
    - left_grip_x_joint
    - left_grip_y_joint
    - left_grip_z_joint
    - left_effector
    - right_clavicle_joint
    - right_shoulder_joint
    - right_elbow
    - right_grip_x_joint
    - right_grip_y_joint
    - right_grip_z_joint
    - right_effector
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []